---
- import_tasks: Debian.yml
  when: ansible_os_family == 'Debian'
- import_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Amazon'
- import_tasks: Amazon.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'Amazon'
- name: create nginx group
  become: yes
  group:
    name: "{{ nginx_group }}"
    state: present
- name: create nginx user
  become: yes
  user:
    name: "{{ nginx_user }}"
    state: present
    group: "{{ nginx_group }}"
    append: yes
    shell: /sbin/nologin
- name: add users to nginx group
  become: yes
  user:
    name: "{{ item }}"
    groups: "{{ nginx_group }}"
    append: yes
  with_items:
    - "{{ ansible_user }}"
    - root
- name: create mount point
  become: yes
  file:
    path: "{{ nginx_mount_point }}"
    state: directory
    owner: root
    group: root
    mode: 0755
- name: create default nginx directories
  become: yes
  file:
    path: "{{ nginx_mount_point }}/{{ item }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0775
  with_items:
    - default
- name: create www symlink in home dir
  become: no
  file:
    src: "{{ nginx_mount_point }}"
    dest: /home/{{ ansible_user }}/www
    state: link
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"